services:
  app:
    image: booking-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      CONNECTION_STRING: "sqlite+aiosqlite:///data/booking.db"
      URL_JOBS: "sqlite:///data/jobs.sqlite"
    volumes:
      - db_volume:/app/data
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '1'
    entrypoint: ["./run.sh", "-d", "/app/data"]

volumes:
  db_volume: