"""add lock timeslot

Revision ID: 22ab64434c62
Revises: ceb09b550c45
Create Date: 2025-03-01 01:02:48.826969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ab64434c62'
down_revision: Union[str, None] = 'ceb09b550c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('lock', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_slots', 'lock')
    # ### end Alembic commands ###
