"""Add date_only computed

Revision ID: 5bc8f205e693
Revises: 95d8ff98b480
Create Date: 2025-05-20 12:57:17.983041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc8f205e693'
down_revision: Union[str, None] = '95d8ff98b480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('date_only', sa.Date(), sa.Computed('DATE(date)', ), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'date_only')
    # ### end Alembic commands ###
