"""add reminder minutes before

Revision ID: b5841c186048
Revises: 5bc8f205e693
Create Date: 2025-05-24 14:31:42.620117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5841c186048'
down_revision: Union[str, None] = '5bc8f205e693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reminder_minutes_before', sa.String(), server_default='[60,15,5]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reminder_minutes_before')
    # ### end Alembic commands ###
